# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - main

pool:
  vmImage: windows-latest  # Especifica el agente Windows

steps:
- script: |
      echo "##vso[task.setvariable variable=JAVA_HOME]C:\Users\matys\.jdks\corretto-11.0.18\bin"
  displayName: 'Set JAVA_HOME'

- task: Maven@3
  inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      goals: 'package'
      options: '-Dmaven.test.failure.ignore=true'

- task: Maven@3
  inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean verify "-Dtest=WikipediaRunner,YoutubeRunner"'

